### ISSUE TITLE
Hello demo, could you help me to find out what problem in my set method? Because i can't got the error when running set method line. Error: "Cannot read field "element" because "hold" is null"

### ISSUE THREAD

**Issue by Ahkhai0225** [bjc1999/DS-Lab#1]
public class MyLinkedList<E> {
    private Node<E> head;
    private Node<E> tail;
    int size;

    public MyLinkedList() {
        this.head = null;
        this.tail = null;
        size=0;
    }
    
    public void addFirst(E e){
        Node<E> newNode=new Node<>(e);
        newNode.next=head;
        head=newNode;
        size++;
        if (tail==null){tail=head;}
    }
    
    public void addLast(E e){
        Node<E> newNode=new Node<>(e);
        if (tail==null){head=tail=newNode;}
        else{
            tail.next=newNode;
            tail=newNode;
        }
        size++;
    }
    
    public void add(int index, E e){
        if (index==0){addFirst(e);}
        if (index>=size){addLast(e);}
        else {
            Node<E> current=head;
            for (int i=1; i<index; i++){
                current=current.next;
            }
            Node<E> newNode=new Node<>(e);
            Node<E> temp=current.next;
            current.next=newNode;
            newNode.next=temp;
            size++;  
        }
    }
    
    public E removeFirst(){
        if (size==0){return null;}
        else{
            Node<E> hold=head;
            head=head.next;
            size--;
            if (head==null){tail=null;}
            return hold.element;
        }       
    }
    
    public E removeLast(){
        if (size==0){return null;}
        if (size==1){
            Node<E> hold=head;
            head=tail=null;
            size=0;
            return hold.element;
        }
        else {
            Node<E> current=head;
            for (int i=1; i<size-1; i++){
                current=current.next;
            }
            Node<E> hold=tail;
            tail=current;
            tail.next=null;
            size--;
            return hold.element;
        }
    }
    
    public E remove(int index){
        if (index==0){removeFirst();}
        if (index==size-1){removeLast();}
        if (size==0 || index>=size){return null;}
        else{
            Node<E> current=head;
            for (int i=1; i<index; i++){
                current=current.next;
            }
                Node<E> hold=current.next;
                current.next=hold.next;
                size--;
                return hold.element;
        }
    }
    
    public void add(E e){
        Random r=new Random();
        int index=r.nextInt(size-1);
        if (index==0){addFirst(e);}
        if (index>=size){addLast(e);}
        else {
            Node<E> current=head;
            for (int i=1; i<index; i++){
                current=current.next;
            }
            Node<E> newNode=new Node<>(e);
            Node<E> temp=current.next;
            current.next=newNode;
            newNode.next=temp;
            size++;  
        }       
    }
    
    public boolean contains(E e){
        if (head.element.equals(e)){return true;}
        Node<E> current=head;
        for (int i=1; i<size; i++){
            current=current.next;
            if (current.element.equals(e)){
                return true;
            }
        }
        return false;
    }
    
    public E get(int index){
        if (index==0){return head.element;}
        if (index==size-1){return tail.element;}
        if (index<0 || index>=size){return null;}
        else{
            Node<E>current=head;
            for (int i=1; i<=index; i++){
                current=current.next;
            }
        return current.element;
        }
    }
    
    public E getFirst(){
        return head.element;
    }
    
    public E getLast(){
        Node<E> current=head;
        for (int i=1; i<size; i++){
            current=current.next;
        }
        return current.element;
    }
    
    public int indexOf(E e){
        if (head.element.equals(e)){return 0;}
        if (tail.element.equals(e)){return size-1;}
        else{
            Node<E> target=head;
            for(int i=1; i<size; i++){
                target=target.next;
                if (target.element.equals(e)){
                    return i;
                }
            }
        }
        return -1;
    }
    
    public int lastIndexOf(E e){
        int cnt=-1;
        Node<E> target=head;
        for (int i=0; i<size; i++){
            if (target.element.equals(e)){
                cnt=i;
            }
            target=target.next;
        }
        return cnt;
    }
    
    public E set(int index, E e){
        if (index<0){return null;}
        else if (index==0){
            Node<E> hold=head;
            head=new Node<>(e);
            return hold.element;
        }
        else if (index>=size){
            Node<E> hold=tail;
            addLast(e);
            return hold.element;
        }
        else{
            Node<E> current=head;
            for (int i=1; i<index; i++){
                current=current.next;
            }
            Node<E> hold=current.next;
            current.next=new Node<>(e);
            return hold.element;    
        }
    }
    
    public void clear(){
        head =null;
        tail=null;
    }
    
    public void print(){
        if (head==null){
            System.out.println("The list is empty");
        }
        Node<E> current=head;
        for (int i=0; i<size; i++){
            if (current.next==null){
                System.out.print(current.element);
            }
            else {
                System.out.print(current.element+", ");
            }
            current=current.next;
        }
        System.out.println();
    }

**Comment by bjc1999** [comment]
Hi, sorry for late reply.
Few things to note on your code:
1. I think maybe you forgot the \<E\> for class signature when you paste your code here (should be `public class MyLinkedList<E>`)
2. You didn't show your `Node` class here so I make assumption that in your `Node` class constructor `public Node (E e)` you set `next` variable to `null`
3. Your `set` method is implemented wrongly in the logical mean. I think question ask you to **replace** instead of just add a new `Node` at the specified index (if I am wrong please correct me)

Okay, so let just assume that you are doing the above thing correctly, the reason of why you are getting `NullPointerException` is:
let's imagine you first set the first `Node` in your `LinkedList` to new element `e`, it execute this part of code:
```
else if (index==0){
    Node<E> hold=head;
    head=new Node<>(e);
    return hold.element;
}
```
please notice here when you create new `Node` for head, you didn't assign anything to your `next` pointer for the new node.

and when you try to set second node in your `LinkedList` to new element `e` after the above operation:
```
else{
    Node<E> current=head;
    for (int i=1; i<index; i++){
        current=current.next;
    }
    Node<E> hold=current.next;
    current.next=new Node<>(e);
    return hold.element;     
}
```
you assign your `hold = current.next` (in this case your current is head) but as I said just now, your new head's `next` pointer is pointing to nothing (because you didn't assign anything to it when you create it) so eventually hold will be equal to `null` and that's why in your return statement when you try to access `hold.element` it give you error.

possible soultion:
```
else if (index==0){
    Node<E> hold=head;
    Node<E> newNode = new Node<>(e);
    newNode.next = head;
    head=newNode;
    return hold.element;
}
```
like what you do for `addFirst`, but `set` method is mean to replace, so technically you should do something like this:
```
else if (index==0){
    Node<E> hold=head;
    Node<E> newNode = new Node<>(e);
    newNode.next = head.next;    // point new node next pointer to next node of original head node
    head=newNode;
    hold.next = null;    // point original head next pointer to null so that it is not related to the linkedlist anymore
    return hold.element;
}
```
OR
```
else if (index==0){
    E hold=head.element;    // hold element instead of node
    head.element = e;    // assign head element to new element e
    return hold;
}
```
and please do the same for other conditions in your `set` method too.

Hopefully you understand what I want to explain here, if still don't understand can keep reply here as well.

**Comment by Ahkhai0225** [comment]
Problem solved, thanks demo

**Comment by bjc1999** [comment]
This problem is solved.
