### ISSUE TITLE
Stack Issue : What is the difference between using "double" and "Double" as return type in methods?

### ISSUE THREAD

**Issue by aimanwafiq12** [bjc1999/DS-Lab#2]
`public class PostfixEvaluation {
    public static void main(String[] args)
    {
        System.out.println("Testing PostfixEvaluation:\n");
        System.out.println("2 3 + 4 * 5 - : "
                + evaluatePostfix("2 3 + 4 * 5 -") + "\n");
        System.out.println("2 3 * 4 2 - / 5 6 * + : "
                + evaluatePostfix("2 3 * 4 2 - / 5 6 * +")
                + "\n");
        System.out.println("2 4 - 3 ^ 5 + : "
                + evaluatePostfix("2 4 - 3 ^ 5 +")
                + "\n");
        System.out.println("\n\nDone.");
    }  // end main

    /** Evaluates a postfix expression.
     @param postfix  a string that is a valid postfix expression.
     @return  the value of the postfix expression. */
    public static double evaluatePostfix(String postfix)   {
        GenericStack<Double> valueStack = new GenericStack<>();
        String[] tokens = postfix.split(" ");
        for (String token: tokens)
        {
            if(isNumeric(token))
            {
                valueStack.push(Double.valueOf(token));
            }
            else if (token.equals("+") || token.equals("-") || token.equals("*")
                    || token.equals("/") || token.equals("^"))
            {
                Double operandTwo = valueStack.pop();
                Double operandOne = valueStack.pop();
                Double result = compute(operandOne, operandTwo, token);
                valueStack.push(result);
            }
        } // end for

        return (valueStack.peek());
    } // end evaluatePostfix

    public static boolean isNumeric(String str)
    {
        try
        {
            double d = Double.parseDouble(str);
        }
        catch(NumberFormatException nfe)
        {
            return false;
        }
        return true;
    }

    private static Double compute(Double operandOne, Double operandTwo, String operator)
    {
        double result;

        switch (operator)
        {
            case "+":
                result = operandOne + operandTwo;
                break;

            case "-":
                result = operandOne - operandTwo;
                break;

            case "*":
                result = operandOne * operandTwo;
                break;

            case "/":
                result = operandOne / operandTwo;
                break;

            case "^":
                result = Math.pow(operandOne, operandTwo);
                break;

            default:    // Unexpected character
                result = 0;
                break;
        } // end switch

        return result;
    } // end compute
}
`

**Comment by NeverOnTimeSdnBhd** [comment]
In Java, `Double` is an object while `double` is a primitive type.
In your case, `Double` and `double` is **totally interchangeable**, consider following few examples, do note that they are **all valid**.
```
public static void main(String[] args) {
    Double num = testDouble();
    System.out.println(num);
}

public static double testDouble() {
    double num = 8.0;
    return num;
}
```
```
public static void main(String[] args) {
    double num = testDouble();
    System.out.println(num);
}

public static Double testDouble() {
    double num = 8.0;
    return num;
}
```
```
public static void main(String[] args) {
    double num = testDouble();
    System.out.println(num);
}

public static double testDouble() {
    Double num = 8.0;
    return num;
}
```
You can try to play with it by trying every possibilities, you will find out no matter how you change `Double` to `double` or vice versa it will work anyway.

However, there is a very important different for object `Double` and primitive type `double`!
Please bear in mind that Java `Generic` type **only accept object but not primitive type**.
This means that
```
Stack<Double> doubleStack = new Stack<>();
```
is valid but
```
Stack<double> doubleStack = new Stack<>();
```
will give you compile time error instead.
Please be aware of this on test tomorrow as this is one of the common mistake made by many people.

**Comment by bjc1999** [comment]
In Java, `Double` is an object while `double` is a primitive type.
In your case, `Double` and `double` is **totally interchangeable**, consider following few examples, do note that they are **all valid**.
```
public static void main(String[] args) {
    Double num = testDouble();
    System.out.println(num);
}

public static double testDouble() {
    double num = 8.0;
    return num;
}
```
```
public static void main(String[] args) {
    double num = testDouble();
    System.out.println(num);
}

public static Double testDouble() {
    double num = 8.0;
    return num;
}
```
```
public static void main(String[] args) {
    double num = testDouble();
    System.out.println(num);
}

public static double testDouble() {
    Double num = 8.0;
    return num;
}
```
You can try to play with it by trying every possibilities, you will find out no matter how you change `Double` to `double` or vice versa it will work anyway.

However, there is a very important different for object `Double` and primitive type `double`!
Please bear in mind that Java `Generic` type **only accept object but not primitive type**.
This means that
```
Stack<Double> doubleStack = new Stack<>();
```
is valid but
```
Stack<double> doubleStack = new Stack<>();
```
will give you compile time error instead.
Please be aware of this on test tomorrow as this is one of the common mistake made by many people.

Thanks for the good question!

**Comment by aimanwafiq12** [comment]
Alright. Thank you Jing Chong for the explanation.
